import { Lesson } from '../types/lesson';

export const SAMPLE_LESSONS: Lesson[] = [
  {
    id: 'lesson-1',
    title: '友達へのあいさつ',
    description: 'カジュアルなあいさつを自然なリズムとイントネーションで練習しよう。',
    category: 'daily',
    level: 'beginner',
    script: "Hey, how's it going? I haven't seen you in ages! We should definitely catch up over coffee sometime.",
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=300&fit=crop',
    durationSeconds: 8,
    order: 1,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-2',
    title: 'カフェで注文する',
    description: 'ドリンクやフードを自信を持って注文する方法を学ぼう。',
    category: 'daily',
    level: 'beginner',
    script: "Hi, could I get a large iced latte with oat milk, please? And maybe a blueberry muffin to go.",
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
    durationSeconds: 7,
    order: 2,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-3',
    title: '面接での自己紹介',
    description: '英語の面接で好印象を与える自己紹介を練習しよう。',
    category: 'business',
    level: 'intermediate',
    script: "Thank you for having me today. I'm really excited about this opportunity. I've been working in software development for five years and I'm passionate about building products that make a difference.",
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1565688534245-05d6b5be184a?w=400&h=300&fit=crop',
    durationSeconds: 12,
    order: 3,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-4',
    title: '道を尋ねる',
    description: '海外旅行で自信を持って道を聞けるようになろう。',
    category: 'travel',
    level: 'beginner',
    script: "Excuse me, could you tell me how to get to the nearest subway station? Is it within walking distance?",
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400&h=300&fit=crop',
    durationSeconds: 7,
    order: 4,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-5',
    title: 'プレゼンテーション',
    description: '英語のプレゼンを自信を持って始めるフレーズを練習しよう。',
    category: 'business',
    level: 'advanced',
    script: "Good morning, everyone. Today I'd like to walk you through our quarterly results and share some exciting updates about our product roadmap for the upcoming year.",
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=400&h=300&fit=crop',
    durationSeconds: 10,
    order: 5,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-6',
    title: '定番イディオム',
    description: '日常でよく使われる英語のイディオムをマスターしよう。',
    category: 'idiom',
    level: 'intermediate',
    script: "It's raining cats and dogs outside, so let's just stay in and binge-watch something. We can kill two birds with one stone by relaxing and improving our English at the same time.",
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=300&fit=crop',
    durationSeconds: 11,
    order: 6,
    createdAt: Date.now(),
  },
];
