import { Lesson } from '../types/lesson';

export const SAMPLE_LESSONS: Lesson[] = [
  {
    id: 'lesson-1',
    title: 'Greeting a Friend',
    description: 'Practice casual greetings with natural rhythm and intonation.',
    category: 'daily',
    level: 'beginner',
    script: "Hey, how's it going? I haven't seen you in ages! We should definitely catch up over coffee sometime.",
    audioUrl: '',
    durationSeconds: 8,
    order: 1,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-2',
    title: 'Ordering at a Cafe',
    description: 'Learn how to order drinks and food confidently.',
    category: 'daily',
    level: 'beginner',
    script: "Hi, could I get a large iced latte with oat milk, please? And maybe a blueberry muffin to go.",
    audioUrl: '',
    durationSeconds: 7,
    order: 2,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-3',
    title: 'Job Interview Introduction',
    description: 'Make a strong first impression in English job interviews.',
    category: 'business',
    level: 'intermediate',
    script: "Thank you for having me today. I'm really excited about this opportunity. I've been working in software development for five years and I'm passionate about building products that make a difference.",
    audioUrl: '',
    durationSeconds: 12,
    order: 3,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-4',
    title: 'Asking for Directions',
    description: 'Navigate confidently when traveling abroad.',
    category: 'travel',
    level: 'beginner',
    script: "Excuse me, could you tell me how to get to the nearest subway station? Is it within walking distance?",
    audioUrl: '',
    durationSeconds: 7,
    order: 4,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-5',
    title: 'Giving a Presentation',
    description: 'Start your English presentations with confidence.',
    category: 'business',
    level: 'advanced',
    script: "Good morning, everyone. Today I'd like to walk you through our quarterly results and share some exciting updates about our product roadmap for the upcoming year.",
    audioUrl: '',
    durationSeconds: 10,
    order: 5,
    createdAt: Date.now(),
  },
  {
    id: 'lesson-6',
    title: 'Common Idioms',
    description: 'Master everyday English idioms and their usage.',
    category: 'idiom',
    level: 'intermediate',
    script: "It's raining cats and dogs outside, so let's just stay in and binge-watch something. We can kill two birds with one stone by relaxing and improving our English at the same time.",
    audioUrl: '',
    durationSeconds: 11,
    order: 6,
    createdAt: Date.now(),
  },
];
